backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "experience"
    label: "Experience"
    folder: "content/exp"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: true
    fields:
      - { label: "Employer", name: "employer", widget: "string" }
      - { label: "Start Date", name: "sdate", widget: "datetime" }
      - { label: "Finish Date", name: "fdate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }